[package]
name = "RazorAmm"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
razor_amm = "_"
admin = "0x380cc51342dc20d61af1a05abbd3a4ba718e555ef8c01f1337698180d5ecff31"
fee_admin = "0x698186149dd784fa8ef5208f7128fda0a4fad9a6c27fe329e3e4ea727d3c5816"
bob = "0xb0b"
alice = "0xa11ce"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev="main", subdir = "aptos-move/framework/aptos-framework" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev="main", subdir = "aptos-move/framework/aptos-stdlib" }

[dev-dependencies]
