[package]
name = "RazorAmm"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
razor_amm = "_"
admin = "0x703c20063317af987ab7fc191103d7cd27369ee1322a90d23b174ee393ca9839"
fee_admin = "0x4b1bf00e6b8dc4a7bc00f9dc02e5da424236afad275c8833b48c54b0496fd283"
bob = "0xb0b"
alice = "0xa11ce"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev="main", subdir = "aptos-move/framework/aptos-framework" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev="main", subdir = "aptos-move/framework/aptos-stdlib" }

[dev-dependencies]
