[package]
name = "RazorAmm"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
razor_amm = "_"
admin = "0x2b9e64c5fad8a9a881a6657b53af04ed1ad6159734a06842e29ef98b1a5f2181"
fee_admin = "0x141f0efdebb2d94806d1ce547e9d6ebd92e8e7163d75a03359e705392b407877"
bob = "0xb0b"
alice = "0xa11ce"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev="main", subdir = "aptos-move/framework/aptos-framework" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev="main", subdir = "aptos-move/framework/aptos-stdlib" }

[dev-dependencies]
